### ISSUE TITLE
With the latest Phile-Version Sitemap under /sitemap.xml not worked

### ISSUE THREAD

**Issue by ghost** [PhileCMS/phileXMLSitemap#5]
Hello Developers,

unfortunately this plugin does not work with the very latest Phile version. In the front end under `/sitemap.xml` comes 404 Error.

Can you please check this again and check it.

I have otherwise installed the plugin and tried with Composer. This result, the sitemap in the frontend is not available.

My Phile-Blog is on a subdomain at https://phile.wpzweinull.ch, so you can see it.

Thanks in advance.

**Comment by Schlaefer** [comment]
Thanks for the heads-up. Should be compatible with latest Phile version again.
